#!/bin/bash 
#NOTE this is just a proof of consept array list that gererates a swear word at you
# I got tired of google searching how to make an bash array list 
#on slow a slow internet connection this is quite useful because it can take google longer to load than your server somethinge 
#I'm starting to have some fun with puns too


export y="printf y"
read -p "do you want this to be shuffled y/n" yn
case $yn in
[Yy]* )
export shuf="--shuf";;
[Nn]* )
export shuf="";;
* ) 
echo "please enter y or n"
esac 
parallel $shuf echo  ::: 'bitch' 'ass' 'fuck' 'cunt' 'shit' 'asshole' 'hell' 'bollocks' 'child-fucker' 'damn' 'crap' 'goddamn' 'motherfucker' 'shitass' 'whore' 'cock-sucker' 'cock' 'fucker' 'shithole' 'assfucker' \
'phucker' 'dick' 'dickhead' 'cocksucker' 'ass-hat' 'assbag' 'assbite' 'assclown' 'assfucker' 'assfuck' 'assface' 'asshat' 'asshead' 'assmonkey' 'assshit' 'asswipe' 'bastard' 'bullshit' 'buttfucker' \
'clusterfuck' 'cockass' 'cockbite' 'cockface' 'cockfucker' 'cock' 'cockmonkey' 'cockshit' 'dickhead' 'dickface' 'dickfucker' 'dickhole' 'dickbag' 'dickweed' 'dipshit' 'dike' 'dbag' 'doochbag' 'dumbass' \
'dumass' 'dumbfuck' 'dumbshit' 'dumshit' 'dyke' 'fatass' 'fuckbutt' 'fuckboy' 'fuckbrain' 'fuckbutt' 'fuckface' 'fucking' 'fuckhole' 'fuckin' 'fucknut' 'fucks' 'fuckoff' 'fucktard' 'fuckup' 'fuckwitt' \
'fuckwad' 'fuckwit' 'gayass' 'goddamnit' 'hoe' 'jackass' 'jagoff' 'lardass' 'mick' 'mothafucka' 'motherfucking' 'pecker' 'pussie' 'pussies' 'prick' 'ruski' 'shitbag' 'shitcunt' 'shitdick' 'shitbrains' \
'shitface' 'shitfaced' 'shithole' 'shithead' 'shitter' 'shitty' 'shiz' 'suckass' 'tard' 'twats' 'thundercunt' 'twatlips' 'mindfuck' 'mindfucker' 'mindfucking' 'hag'  ::: 'bitch' 'ass' 'fuck' 'cunt' 'shit' 'asshole' 'hell' 'bollocks' 'child-fucker' 'damn' 'crap' 'goddamn' 'motherfucker' 'shitass' 'whore' 'cock-sucker' 'cock' 'fucker' 'shithole' 'assfucker'
'phucker' 'dick' 'dickhead' 'cocksucker' 'ass-hat' 'assbag' 'assbite' 'assclown' 'assfucker' 'assfuck' 'assface' 'asshat' 'asshead' 'assmonkey' 'assshit' 'asswipe' 'bastard' 'bullshit' 'buttfucker' \
'clusterfuck' 'cockass' 'cockbite' 'cockface' 'cockfucker' 'cock' 'cockmonkey' 'cockshit' 'dickhead' 'dickface' 'dickfucker' 'dickhole' 'dickbag' 'dickweed' 'dipshit' 'dike' 'dbag' 'doochbag' 'dumbass' \
'dumass' 'dumbfuck' 'dumbshit' 'dumshit' 'dyke' 'fatass' 'fuckbutt' 'fuckboy' 'fuckbrain' 'fuckbutt' 'fuckface' 'fucking' 'fuckhole' 'fuckin' 'fucknut' 'fucks' 'fuckoff' 'fucktard' 'fuckup' 'fuckwitt' \
'fuckwad' 'fuckwit' 'gayass' 'goddamnit' 'hoe' 'jackass' 'jagoff' 'lardass' 'mick' 'mothafucka' 'motherfucking' 'pecker' 'pussie' 'pussies' 'prick' 'ruski' 'shitbag' 'shitcunt' 'shitdick' 'shitbrains' \
'shitface' 'shitfaced' 'shithole' 'shithead' 'shitter' 'shitty' 'shiz' 'suckass' 'tard' 'twats' 'thundercunt' 'twatlips' 'mindfuck' 'mindfucker' 'mindfucking' 'hag'  
#echo $bitch
