#!/bin/bash 
# https://en.wikipedia.org/wiki/List_of_the_most_common_passwords

export y="printf y"
read -p "do you want this to be shuffled y/n" yn
case $yn in
[Yy]* )
export shuf="--shuf";;
[Nn]* )
export shuf="";;
* ) 
echo "please enter y or n"
esac 
parallel $shuf  echo {1}{2}  ::: 'password' 'Password' 'P@assw0rd' 'admin' 'Admin' 'root' 'toor' '123456' '12345678' '123456789' '0123456' '1234567890' 'cute' 'Cute' 'Cubs' 'cubs' 'CubsCubs' 'cubscubs' \
'raspberry' 'pi' '123' '1234' 'cutie' 'Cutie' 'cisco' 'Cisco' '11111111' '99999999' '0987654321' '987654321' 'qwerty' 'letmein' 'LetMeIn' 'QWERTY' '12345' '1234567' 'football' 'welcome' 'iloveyou' \
'Welcome' 'Iloveyou' 'monkey' 'Monkey' 'login' 'abc' 'abc123' 'starwars' 'passw0rd' 'Passw0rd' 'master' 'Master' 'hello' 'Hello' 'freedom' 'whatever' 'qazwsx' 'trustno1' 'TrustNo1' 'Trustno1' \
'trustnoone' 'TrustNoOne' 'TrustnoOne' 'Freedom' 'Whatever' 'WhatEver' '111111' 'sunshine' 'Sunshine' 'princess' 'Princess' '666666' '!@#$%^&*' 'charlie' 'Charlie' 'aa123456' 'AA123456' 'donald' \
'Donald' 'password1' 'qwerty123' 'Qwerty123' 'Qwerty' 'Passowrd1' 'dragon' 'Dragon' '1234' 'solo' 'SOLO' 'Solo' 'ADMIN' 'PASSWORD' 'PASSW0RD' 'P@SSW0RD' 'P@ssword' 'P@SSWORD' 'flower' 'Flower' \
'hottie' 'Hottie' 'loveme' 'Loveme' 'zaq1zaq1' 'qwertyuiop' 'baseball' 'Baseball' 'mustang' 'Mustang' 'Access' 'access' 'shadow' 'Shadow' 'michael' 'Michael' 'superman' 'Superman' '696969' 'batman' \
'Batman' 'adobe123' 'Adobe123' 'photoshop' 'Photoshop' 'azerty' '000000' 'ninja' 'Ninja' 'jesus' 'Jesus' 'ashley' '654321' 'Ashley' ::: '' '1' '2' '3' '4' '5' '6' '7' '8' '9' '0' '10' '11' '12' '22' \
'33' '44' '55' '66' '666' '77' '88' '99' '00' '69' '!' '!!'
