#!/bin/bash
source $PROG/generate_ctp-dns-envs.sh $@

OUT_FILE=$BACKUP_RESOVLERS_FILE

DOMAIN=master.dns.ctptech.dev
IP_ADDRESSES=`bash $PROG/get_ext_ip.sh $DOMAIN`
if [[ $IP_ADDRESSES =~ ((([0-9]{1,3}\.)?){4}) ]]; then
echo """# Generated by: $scriptName
# Generated at: `date`


""" | sudo tee $OUT_FILE


for ip in $IP_ADDRESSES
do
	ip_title=${ip//\./-}
	dot="$NGINX_RESOLVER-$ip_title-dot"
	dtls="$NGINX_RESOLVER-$ip_title-dtls"

echo """
# DoT
[resolvers.$dot]
address = \"$DOMAIN:11853\"
protocol = \"dot\"
bootstrap-address = \"$ip\"
# DTLS

""" | sudo tee -a $OUT_FILE

done

export BACKUP_RESOLVERS_LIST=$(grep -E "^.resolvers\..*$NGINX_RESOLVER.*" $OUT_FILE | awk -F. '{print $2}' | awk -F] '{print $1}')
export BACKUP_RESOLVERS=$(bash $PROG/new_linify.sh $(bash $PROG/csvify.sh $(printf '%s\n' "$BACKUP_RESOLVERS_LIST" ) --quotes --space))

echo """
# FALLBACK
[groups.$NGINX_RESOLVER_GROUP-fail-back]
resolvers = [
        $BACKUP_RESOLVERS
]
type = \"fail-back\"
reset-after = $timeout
servfail-error = true

# FASTEST
[groups.$NGINX_RESOLVER_GROUP-fastest]
resolvers = [
	$BACKUP_RESOLVERS
]
type = \"fastest\"
""" | sudo tee -a $OUT_FILE

format_file $OUT_FILE
fi
