#!/bin/bash
source $PROG/all-scripts-exports.sh
what_system
source $PROG/populae-log.sh
OUT_FILE=$DNSMASQ/10-servers-generated-for-cache-interface-and-freq-queries.conf

FILE_W=$HOLE/quick-whitelist.list
FILE_B=$HOLE/quick-blacklist.list

mapfile -t DOMAINS_TO_TEST_WHITE < $FILE_W
declare -a all_domains
all_domains=(
	${DOMAINS_TO_TEST_WHITE[@]}
)
FILTER_LIST_GREPIFYED='google\|gstatic\|ytimg\|yimg\|youtube\|ampproject\|optimizely\|gmail\|ggpht.com\|recaptcha.net'

DOMAINS_TO_TEST_WHITE=( $(bash $PROG/new_linify.sh  ${DOMAINS_TO_TEST_WHITE[@]} | grep -v "$FILTER_LIST_GREPIFYED" ) )
SMALL_DOMAINS_LIST=( $(bash $PROG/new_linify.sh  ${SMALL_DOMAINS_LIST[@]} | grep -v "$FILTER_LIST_GREPIFYED" ) )
EXTRA_DOMAINS_LIST=( $(bash $PROG/new_linify.sh  ${EXTRA_DOMAINS_LIST[@]} | grep -v "$FILTER_LIST_GREPIFYED" ) )

echo """# Generated by: $scriptName
# Generated at: `date`
# This reduces system resource usage and log output

""" | sudo tee $OUT_FILE

echo """
# DOMAINS_TO_TEST_WHITE
""" | sudo tee -a $OUT_FILE
if [[ $IS_GCP == true ]]; then
	echo "$(bash $PROG/dnsmasqify.sh ${DOMAINS_TO_TEST_WHITE[@]})" | parallel --lb echo 'server={}169.254.169.254' | sudo tee -a $OUT_FILE
fi
echo "$(bash $PROG/dnsmasqify.sh ${DOMAINS_TO_TEST_WHITE[@]})" | parallel --lb echo 'server={}1.1.1.1' | sudo tee -a $OUT_FILE
echo "$(bash $PROG/dnsmasqify.sh ${DOMAINS_TO_TEST_WHITE[@]})" | parallel --lb echo 'server={}8.8.8.8' | sudo tee -a $OUT_FILE
echo "$(bash $PROG/dnsmasqify.sh ${DOMAINS_TO_TEST_WHITE[@]})" | parallel --lb echo 'server={}9.9.9.9' | sudo tee -a $OUT_FILE

echo """
# SMALL_DOMAINS_LIST
""" | sudo tee -a $OUT_FILE
if [[ $IS_GCP == true ]]; then
	echo "$(bash $PROG/dnsmasqify.sh ${SMALL_DOMAINS_LIST[@]})" | parallel --lb echo 'server={}169.254.169.254' | sudo tee -a $OUT_FILE
fi
echo "$(bash $PROG/dnsmasqify.sh ${SMALL_DOMAINS_LIST[@]})" | parallel --lb echo 'server={}1.1.1.1' | sudo tee -a $OUT_FILE
echo "$(bash $PROG/dnsmasqify.sh ${SMALL_DOMAINS_LIST[@]})" | parallel --lb echo 'server={}8.8.8.8' | sudo tee -a $OUT_FILE
echo "$(bash $PROG/dnsmasqify.sh ${SMALL_DOMAINS_LIST[@]})" | parallel --lb echo 'server={}9.9.9.9' | sudo tee -a $OUT_FILE

echo """
# EXTRA_DOMAINS_LIST
""" | sudo tee -a $OUT_FILE

if [[ $IS_GCP == true ]]; then
	echo "$(bash $PROG/dnsmasqify.sh ${EXTRA_DOMAINS_LIST[@]})" | parallel --lb echo 'server={}169.254.169.254' | sudo tee -a $OUT_FILE
fi
echo "$(bash $PROG/dnsmasqify.sh ${EXTRA_DOMAINS_LIST[@]})" | parallel --lb echo 'server={}1.1.1.1' | sudo tee -a $OUT_FILE
echo "$(bash $PROG/dnsmasqify.sh ${EXTRA_DOMAINS_LIST[@]})" | parallel --lb echo 'server={}8.8.8.8' | sudo tee -a $OUT_FILE
echo "$(bash $PROG/dnsmasqify.sh ${EXTRA_DOMAINS_LIST[@]})" | parallel --lb echo 'server={}9.9.9.9' | sudo tee -a $OUT_FILE
