#!/bin/bash
source $PROG/generate_ctp-dns-envs.sh --do-well-knowns $@

OUT_FILE=$WELL_KN_RESOVLERS_RT_GROUPS_FILE
OUT_FILE_R=$WELL_KN_RESOVLERS_RT_RAW_GROUPS_FILE


echo """# Generated by: $scriptName
# Generated at: `date`


""" | sudo tee $OUT_FILE


search_resolver_type='dtls'
search_resolver_type_reverse='dot'

WELL_KNOWN_RESOLVERS_LIST_SEARCH_TYPE_ONLY=$( printf '%s\n' "$WELL_KNOWN_RESOLVERS_LIST" | grep -i "$search_resolver_type" )
IFS=$'\n'

for resolver in $WELL_KNOWN_RESOLVERS_LIST_SEARCH_TYPE_ONLY
do
	echo "On $resolver"
	resolver_root_name=$( echo "$resolver" | awk -F"-$search_resolver_type" '{print $1}' )
	resolver_end_type=$( echo "$resolver" | awk -F"$search_resolver_type-" '{print $2}' )
	is_better_half=`printf '%s\n' "$WELL_KNOWN_RESOLVERS_LIST" | grep -o "$resolver_root_name-$search_resolver_type_reverse-$resolver_end_type"`

	if [[ -n $is_better_half ]]; then

echo """

# Well Known $resolver_root_name IP $resolver_end_type
[groups.$WELL_KN_TRUCATE_GROUP_E-$resolver_root_name-ip-$resolver_end_type]
type = \"truncate-retry\"
resolvers = [ \"$resolver\" ]
retry-resolver = \"$resolver_root_name-$search_resolver_type_reverse-$resolver_end_type\"
""" | sudo tee -a $OUT_FILE

	fi
done

echo """# Generated by: $scriptName
# Generated at: `date`


""" | sudo tee $OUT_FILE_R




search_resolver_type='udp'
search_resolver_type_reverse='tcp'

WELL_KNOWN_RESOLVERS_LIST_SEARCH_TYPE_ONLY=$( printf '%s\n' "$WELL_KNOWN_RESOLVERS_RAW_LIST" | grep -i "$search_resolver_type" )

for resolver in $WELL_KNOWN_RESOLVERS_LIST_SEARCH_TYPE_ONLY
do
	echo "On $resolver"
	resolver_root_name=$( echo "$resolver" | awk -F"-$search_resolver_type" '{print $1}' )
	resolver_end_type=$( echo "$resolver" | grep -E '[0-9]' )
	[[ -n "$resolver_end_type" ]] && resolver_end_type_regex="|$resolver_end_type"
	is_better_half=`printf '%s\n' "$WELL_KNOWN_RESOLVERS_RAW_LIST" | grep -oE "($resolver_root_name|$search_resolver_type_reverse$resolver_end_type_regex|(-)?)+" | sort -u`

	if [[ -n $is_better_half ]]; then
echo """

# Well Known $resolver_root_name IP $resolver_end_type
[groups.$WELL_KN_TRUCATE_GROUP-$resolver_root_name-ip]
type = \"truncate-retry\"
resolvers = [ \"$resolver\" ]
retry-resolver = \"$resolver_root_name-tcp\"
""" | sudo tee -a $OUT_FILE_R

	fi
done



format_file $OUT_FILE
format_file $OUT_FILE_R
