# The bootstrap-resolver is loaded first and used for endpoint lookups as well as blocklist addresses. If the bootstrap-resolver itself uses a hostname, it's possible to configure a 
# bootstrap-address for it.
[bootstrap-resolver]
address = "1.1.1.1:853"
protocol = "dot"

[groups.minimize]
type = "response-minimize"
resolvers = [ "root-router" ]

[groups.collapse]
type = "response-collapse"
resolvers = [ "root-router" ]

[groups.ctp-dns-cached]
type = "cache"
resolvers = [ "ctp-dns-min-ttl" ]
cache-negative-ttl = 3600
cache-size = 50000
cache-answer-shuffle = "round-robin"

[groups.ctp-dns-cached-front]
type = "cache"
resolvers = [ "root-router" ]
cache-negative-ttl = 3600
cache-size = 5000
cache-answer-shuffle = "round-robin"

[groups.static-rfc8482]
type   = "static-responder"
answer = [ 
	"IN HINFO RFC8482 ANY obsoleted!", 
	"IN A 0.0.0.0",
	"IN AAAA ::",
	"IN AAAA ::0",
]
rcode  = 5

[groups.static-refuse]
type = "static-responder"
answer = [ 
	"IN A 0.0.0.0", 
	"IN AAAA ::",
	"IN AAAA ::0",
]
rcode = 5

[routers.root-router]
routes = [
  { class = "ANY", resolver = "static-rfc8482" }, # Send queries of type ANY to a static responder
  { types = [ "RRSIG", "ANY", "SOA", "TXT", "PTR" ], resolver = "static-refuse" }, # Send queries of type RRSIG to a static responder
  { name = '(^|\.)(doubleclick)\.net\.$', resolver = "static-badalg" },
  { name = '(^|\.)(youtube|ytimg|ggpht|youtube-ui\.l\.google|youtubei\.googleapis)\.com\.$', resolver = "ctp-yt-blocker-if-fowarder-router" },
  { name = '(^|\.)(gvt[0-6]?|googlevideo)\.com\.$', resolver = "ctp-yt-blocker-if-fowarder-router" },
  { name = '(^|\.)(fwmrm)\.net\.$', resolver = "ctp-yt-blocker-if-fowarder-router" },
  { name = '(^|\.)(googlesyndication|googleadservices|imrworldwide|adservices\.google)\.com\.$', resolver = "ctp-yt-blocker-if-fowarder-router" },
  { resolver = "ctp-dns-cached" },             # All other queries are forwarded
]

[groups.ctp-dns-min-ttl]
type = "ttl-modifier"
#resolvers = [ "ctp-dns-ecs" ]
resolvers = [ "ctp-dns-group-fastest-tcp-probe-out" ]
ttl-min = 3600
ttl-max = 3024000

[groups.static-servfail]
type   = "static-responder"
answer = [ 
	"IN A 35.232.120.211", 
	"IN A 35.192.105.158",  
	"IN AAAA ::",
	"IN AAAA ::0",
	"IN SRV 0 0 3000 gcp.ctptech.dev.",
]


[groups.static-badalg]
type   = "static-responder"
 # Response code: 0 = NOERROR, 1 = FORMERR, 2 = SERVFAIL, 3 = NXDOMAIN, 5 = REFUSED... 
# https://datatracker.ietf.org/doc/html/rfc2929#section-2.3
rcode  = 21

# Order matters
[groups.ctp-dns-failover]
resolvers = [ 
	"ctp-dns-group", 
	"ctp-dns-fail-rotate",
	"ctp-dns_nginx-back-up-group-fail-back",
	"ctp-dns-failover-backup"
]
reset-after = 45
type = "fail-back"
#servfail-failover = true
servfail-error = true

# Order matters
[groups.ctp-dns-fail-rotate]
resolvers = [
	"ctp-dns-local-master-tcp",
	"ctp-dns-local-master-udp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-tcp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-udp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-dot",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-dot-nginx",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-dtls",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-doq",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-doh-doq",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-doh-get",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-doh-post",
	"ctp-dns_nginx-back-up-group-fail-back",


]

reset-after = 30
type = "fail-rotate"
servfail-error = true

[groups.ctp-dns-ecs]
type = "ecs-modifier"
resolvers = [ "ctp-dns-blocklist" ]
 # "add", "delete", "privacy". Defaults to "" which does nothing.
ecs-op = "add"
ecs-prefix4 = 24
ecs-prefix6 = 64

# CTP INSTALL -- DO NOT REMOVE THIS UNLESS YOU PLAN ON REMOVING INSTALL AND REINSTALLING
