# The bootstrap-resolver is loaded first and used for endpoint lookups as well as blocklist addresses. If the bootstrap-resolver itself uses a hostname, it's possible to configure a 
# bootstrap-address for it.
[bootstrap-resolver]
address = "1.1.1.1:853"
protocol = "dot"

[groups.minimize]
type = "response-minimize"
resolvers = [ "root-router" ]

[groups.collapse]
type = "response-collapse"
resolvers = [ "root-router" ]

[groups.ctp-dns-cached]
type = "cache"
resolvers = [ "ctp-yt-blocker-if-fowarder-router" ]
cache-negative-ttl = 3600
cache-size = 50000
cache-answer-shuffle = "round-robin"

[groups.static-rfc8482]
type   = "static-responder"
answer = ["IN HINFO RFC8482 ANY obsoleted!"]

[routers.root-router]
routes = [
  { type = "ANY", resolver="static-rfc8482" }, # Send queries of type ANY to a static responder
  { resolver = "ctp-dns-min-ttl" },             # All other queries are forwarded
]

[groups.ctp-dns-min-ttl]
type = "ttl-modifier"
#resolvers = [ "ctp-dns-ecs" ]
resolvers = [ "ctp-dns-group-fastest-tcp-probe-out" ]
ttl-min = 1600
ttl-max = 3024000

[groups.static-servfail]
type   = "static-responder"
answer = [ "IN A 35.232.120.211", "IN A 35.192.105.158" ]
# Response code: 0 = NOERROR, 1 = FORMERR, 2 = SERVFAIL, 3 = NXDOMAIN, 5 = REFUSED... 
# https://datatracker.ietf.org/doc/html/rfc2929#section-2.3
rcode  = 3

# Order matters
[groups.ctp-dns-failover]
resolvers = [ 
	"ctp-dns-group", 
	"ctp-dns-fail-rotate",
	"ctp-dns-failover-backup"
]
timeout = 3
type = "fail-back"
servfail-failover = true

# Order matters
[groups.ctp-dns-fail-rotate]
resolvers = [
	"ctp-dns_home-dot",
	"ctp-dns_home-dtls",
	"ctp-dns_home-doh-get",
	"ctp-dns_home-doh-post",
	"ctp-dns_home-doh-get-route-dns-raw",
	"ctp-dns_home-doh-post-route-dns-raw",
	"ctp-dns_home-quic",
	"ctp-dns_home-doh-quic-post-ip",
	"ctp-dns_home-doh-quic-get-ip",
	"ctp-dns-ip-gcp-1-tcp",
	"ctp-dns-ip-gcp-1-udp",
	"ctp-dns-ip-gcp-2-tcp",
	"ctp-dns-ip-gcp-2-udp",
	"ctp-dns-ip-home-tcp",
	"ctp-dns-ip-home-udp"
]
timeout = 3
type = "fail-rotate"
servfail-failover = true

[groups.ctp-dns-ecs]
type = "ecs-modifier"
resolvers = [ "ctp-dns-blocklist" ]
 # "add", "delete", "privacy". Defaults to "" which does nothing.
ecs-op = "add"
ecs-prefix4 = 24
ecs-prefix6 = 64

