#!/bin/bash
source tailscale_sync_client_env.sh
[[ -f $PROG/all-scripts-exports.sh ]] && source $PROG/all-scripts-exports.sh
CROND=/etc/cron.d/
CRON_FILE=tailscale_sync_client_cron

CRON_FILE_PATH=$CROND$CRON_FILE

SHELL_FOR_CRON='SHELL=/bin/bash'
HOUR_TIME=60

S="""
$SHELL_FOR_CRON
MAILTO=\"\"
# Past the Hour intervail aliases
P25=\"$(bash $PROG/csvify.sh $(i=25; seq $i $i $(( $HOUR_TIME )) ) )\"
P20=\"$(bash $PROG/csvify.sh $(i=20; seq $i $i $(( $HOUR_TIME )) ) )\"
P15=\"$(bash $PROG/csvify.sh $(i=15; seq $i $i $(( $HOUR_TIME )) ) )\"
P10=\"$(bash $PROG/csvify.sh $(i=10; seq $i $i $(( $HOUR_TIME )) ) )\"
P5=\"$(bash $PROG/csvify.sh $(i=5; seq $i $i $(( $HOUR_TIME )) ) )\"
P2=\"$(bash $PROG/csvify.sh $(i=2; seq $i $i $(( $HOUR_TIME )) ) )\"
"""

echo """# Generated by: $scriptName
# Generated at: `date`
# Created to sync files in tailscale systems
# Should run once on tailscale setup and then be automatinating itself by updating itself
# No matincace script
$S

""" | sudo tee $CRON_FILE_PATH
for file in ${prog_files_array[@]}
do
	cmd_str="$PROG/tailscale_sync_client.sh $file $PROG"
	echo -e " 58 *   *   *   *    root	$cmd_str" | sudo tee -a $CRON_FILE_PATH
done
