[resolvers.cloudflare-doh-quic]
address = "https://cloudflare-dns.com/dns-query"
protocol = "doh"
transport = "quic"

[resolvers.cloudflare-dot-1]
address = "1.1.1.1:853"
protocol = "dot"

[resolvers.cloudflare-dot-2]
address = "1.0.0.1:853"
protocol = "dot"

[resolvers.google-dot-1]
address = "8.8.8.8:853"
protocol = "dot"

[resolvers.google-dot-2]
address = "8.8.4.4:853"
protocol = "dot"

[resolvers.adguard-dot-1]
address = "94.140.14.14:853"
protocol = "dot"

[resolvers.adguard-dot-2]
address = "94.140.15.15:853"
protocol = "dot"

[resolvers.unbound-failover-tcp]
address = "127.0.0.1:5053"
protocol = "tcp"

[resolvers.unbound-failover-udp]
address = "127.0.0.1:5053"
protocol = "udp"


[groups.ctp-dns-failover-backup]
resolvers = [ "adguard-dot-1", "adguard-dot-2", "unbound-failover-udp", "unbound-failover-tcp", "google-dot-1", "google-dot-2", "cloudflare-dot-1", "cloudflare-dot-2", "cloudflare-doh-quic" ]
type = "fail-back"
