[groups.ctp-dns-failover-backup]
resolvers = [ 
	"adguard-dtls-1",
	"adguard-dtls-2",
	"adguard-dot-1", 
	"adguard-dot-2", 
        "cloudflare-adblock-ip-1-tcp",
        "cloudflare-adblock-ip-1-udp",
        "cloudflare-adblock-ip-2-tcp",
        "cloudflare-adblock-ip-2-udp", 
	"unbound-failover-udp", 
	"unbound-failover-tcp", 
	"cloudflare-dtls-1",
	"cloudflare-dtls-2",
	"cloudflare-dot-1", 
	"cloudflare-dot-2", 
	"google-dtls-1",
	"google-dtls-2",
	"google-dot-1", 
	"google-dot-2", 
	"cloudflare-doh-quic",
	"adguard-doq",
	"cloudflare-ip-1-tcp",
	"cloudflare-ip-1-udp",
	"google-dns-ip-1-tcp",
	"google-dns-ip-1-udp",
	"cloudflare-ip-2-tcp",
	"cloudflare-ip-2-udp",
	"google-dns-ip-2-tcp",
	"google-dns-ip-2-udp",
]
servfail-error = false
timeout = 15
type = "fail-back"
