[routers.ctp-yt-blocker-if-fowarder-router] 
routes = [
  { name = '(youtube)?(ytimg)?(ggpht)?\.com\.$', resolver="ctp-dns-yt-block-resolver-blocker" },
  { name = 'gvt[0-6]?\.com\.$', resolver="ctp-dns-yt-block-resolver-blocker-google-video" },
  { name = 'googlevideo\.com\.$', resolver="ctp-dns-yt-block-resolver-blocker-google-video" },
  { name = '(app-measurement)?(youtubei\.googleapis)?\.com\.$', resolver="ctp-dns-yt-block-resolver-blocker" },
  { name = '(doubleclick)?(fwmrm)?\.net\.$', resolver="ctp-dns-yt-block-resolver-blocker" },
  { name = '(googlesyndication)?(googleadservices)?(imrworldwide)?\.com\.$', resolver="ctp-dns-yt-block-resolver-blocker" },
  { resolver = "root-router" },             # All other queries are forwarded
]
[groups.ctp-dns-yt-block-resolver-blocker]
# This should only be GCP
# "ctp-dns-group"
type = "fastest"

# CTP INSTALL -- DO NOT REMOVE THIS UNLESS YOU PLAN ON REMOVING INSTALL AND REINSTALLING
resolvers = [  "ctp-dns-gcp-dtls", "ctp-dns-gcp-dot", "ctp-dns-master-doh-gcp-quic", "ctp-dns-master-gcp-quic", "ctp-dns-master-doh-gcp-post", "ctp-dns-master-doh-gcp-get" ]
