[routers.ctp-yt-blocker-if-fowarder-router]
routes = [
  { name = '(^|\.)(youtube|ytimg|ggpht)\.com\.$', resolver="ctp-dns-yt-block-resolver-blocker-minimize" },
  { name = '(^|\.)gvt[0-6]?\.com\.$", resolver="ctp-dns-yt-block-resolver-blocker-minimize" },
  { name = '(^|\.)(googlevideo|app-measurement|youtubei\.googleapis)\.com\.$', resolver="ctp-dns-yt-block-resolver-blocker-minimize" },
  { name = '(^|\.)(doubleclick|fwmrm)\.net\.$', resolver="ctp-dns-yt-block-resolver-blocker-minimize" },
  { name = '(^|\.)(googlesyndication|googleadservices|imrworldwide)\.com\.$', resolver="ctp-dns-yt-block-resolver-blocker-minimize" },
  { resolver = "root-router" },             # All other queries are forwarded
]

[groups.ctp-dns-yt-block-resolver-blocker-minimize]
type = "response-minimize"
resolvers = [ "ctp-dns-yt-block-resolver-blocker-collapse" ]

[groups.ctp-dns-yt-block-resolver-blocker-collapse]
type = "response-collapse"
resolvers = [ "ctp-dns-yt-block-resolver-blocker" ]

[groups.ctp-dns-yt-block-resolver-blocker]
# This should only be GCP
# "ctp-dns-group"
type = "fastest"

resolvers = [  "ctp-dns-group" ]

