[routers.ctp-dns-time-router-general-gcp]
routes = [
  { after = "05:20",  before = "01:25", resolver = "ctp-dns-failover" },
  { resolver = "ctp-dns-group-local" },
]
[routers.ctp-dns-time-router-yt-gcp]
routes = [
  { after = "05:20", before = "01:25", resolver = "ctp-dns-yt-block-resolver-blocker" },
  { resolver = "ctp-dns-group-local" },
]
[routers.ctp-dns-time-router-yt-ttl-gcp]
routes = [
  { after = "05:20", before = "01:25", resolver = "ctp-dns-yt-block-resolver-blocker-google-video-ttl" },
  { resolver = "ctp-dns-group-local" },
]
