
[resolvers.ctp-dns-local-master-tcp]
address = "192.168.44.250:53"
protocol = "tcp"
[resolvers.ctp-dns-local-master-udp]
address = "192.168.44.250:53"
protocol = "udp"
edns0-udp-size = 1460

[groups.ctp-dns-local-master-truncate-retry]
type = "truncate-retry"
resolvers = [ "ctp-dns-local-master-udp" ]
retry-resolver = "ctp-dns-local-master-tcp"



[resolvers.ctp-dns-local-master-192-168-44-250-tcp]
address = "192-168-44-250:53"
protocol = "tcp"
[resolvers.ctp-dns-local-master-192-168-44-250-udp]
address = "192-168-44-250:53"
protocol = "udp"
edns0-udp-size = 1460

[groups.ctp-dns-local-master-192-168-44-250-truncate-retry]
type = "truncate-retry"
resolvers = [ "ctp-dns-local-master-192-168-44-250-udp" ]
retry-resolver = "ctp-dns-local-master-192-168-44-250-tcp"



[resolvers.ctp-dns-local-master-192-168-12-250-tcp]
address = "192-168-12-250:53"
protocol = "tcp"
[resolvers.ctp-dns-local-master-192-168-12-250-udp]
address = "192-168-12-250:53"
protocol = "udp"
edns0-udp-size = 1460

[groups.ctp-dns-local-master-192-168-12-250-truncate-retry]
type = "truncate-retry"
resolvers = [ "ctp-dns-local-master-192-168-12-250-udp" ]
retry-resolver = "ctp-dns-local-master-192-168-12-250-tcp"



[resolvers.ctp-dns-local-master-192-168-42-250-tcp]
address = "192-168-42-250:53"
protocol = "tcp"
[resolvers.ctp-dns-local-master-192-168-42-250-udp]
address = "192-168-42-250:53"
protocol = "udp"
edns0-udp-size = 1460

[groups.ctp-dns-local-master-192-168-42-250-truncate-retry]
type = "truncate-retry"
resolvers = [ "ctp-dns-local-master-192-168-42-250-udp" ]
retry-resolver = "ctp-dns-local-master-192-168-42-250-tcp"



[groups.ctp-dns-group]
resolvers = [
	"ctp-dns-local-master-tcp",
	"ctp-dns-local-master-udp",
	"ctp-dns-local-master-192-168-44-250-tcp",
	"ctp-dns-local-master-192-168-44-250-udp",
	"ctp-dns-local-master-192-168-12-250-tcp",
	"ctp-dns-local-master-192-168-12-250-udp",
	"ctp-dns-local-master-192-168-42-250-tcp",
	"ctp-dns-local-master-192-168-42-250-udp",

	"ctp-dns_gcp-dot-ip-1",
	"ctp-dns_gcp-dot-ip-2",
	"ctp-dns_gcp-dtls-ip-1",
	"ctp-dns_gcp-dtls-ip-2",
	"ctp-dns_gcp-doh-post-ip-1",
	"ctp-dns_gcp-doh-post-ip-2",
	"ctp-dns_gcp-doh-get-ip-1",
	"ctp-dns_gcp-doh-get-ip-2",
	"ctp-dns_gcp-doh-quic-post-ip-1",
	"ctp-dns_gcp-doh-quic-post-ip-2",
	"ctp-dns_gcp-doh-quic-get-ip-1",
	"ctp-dns_gcp-doh-quic-get-ip-2",
	"ctp-dns_gcp-quic-ip-1",
	"ctp-dns_gcp-quic-ip-2",

]
type = "fastest"

[groups.ctp-dns-group-local]
resolvers = [
	"ctp-dns-local-master-tcp",
	"ctp-dns-local-master-udp",
	"ctp-dns-local-master-192-168-44-250-tcp",
	"ctp-dns-local-master-192-168-44-250-udp",
	"ctp-dns-local-master-192-168-12-250-tcp",
	"ctp-dns-local-master-192-168-12-250-udp",
	"ctp-dns-local-master-192-168-42-250-tcp",
	"ctp-dns-local-master-192-168-42-250-udp",

]
type = "fastest"

# CTP INSTALL -- DO NOT REMOVE THIS UNLESS YOU PLAN ON REMOVING INSTALL AND REINSTALLING
# NO CHANGES
