[routers.ctp-yt-blocker-if-fowarder-router] 
routes = [
  { name = '(youtube|ytimg|ggpht|youtube-ui\.l\.google|youtubei\.googleapis)\.com\.$', resolver="ctp-dns-time-router-yt-gcp" },
  { name = '^(redirector|manifest|r([0-9]{1,2}){.{4,27}})\.gvt[0-6]?\.com\.$', resolver="ctp-dns-time-router-yt-ttl-gcp" },
  { name = '(^|\.|^redirector\.|^manifest\.)googlevideo\.com\.$', resolver="ctp-dns-time-router-yt-ttl-gcp" },
  { name = '(doubleclick|fwmrm)\.net\.$', resolver="ctp-dns-time-router-yt-gcp" },
  { name = '(googlesyndication|googleadservices|imrworldwide)\.com\.$', resolver="ctp-dns-time-router-yt-gcp" },
  { resolver = "root-router" },             # All other queries are forwarded
]
#doubleclick
[groups.ctp-dns-yt-block-resolver-blocker]
# This should only be GCP
# "ctp-dns-group"
type = "fastest"
# CTP INSTALL -- DO NOT REMOVE THIS UNLESS YOU PLAN ON REMOVING INSTALL AND REINSTALLING
resolvers = [
	"ctp-dns_gcp-dot-ip-1",
	"ctp-dns_gcp-dot-ip-2",
	"ctp-dns_gcp-dtls-ip-1",
	"ctp-dns_gcp-dtls-ip-2",
	"ctp-dns_gcp-doh-post-ip-1",
	"ctp-dns_gcp-doh-post-ip-2",
	"ctp-dns_gcp-doh-get-ip-1",
	"ctp-dns_gcp-doh-get-ip-2",
	"ctp-dns_gcp-doh-quic-post-ip-1",
	"ctp-dns_gcp-doh-quic-post-ip-2",
	"ctp-dns_gcp-doh-quic-get-ip-1",
	"ctp-dns_gcp-doh-quic-get-ip-2",
	"ctp-dns_gcp-quic-ip-1",
	"ctp-dns_gcp-quic-ip-2"
]
