[groups.ctp-dns-blocklist-vulnerability]
type = "cache"
cache-flush-query = "dns.ctptech.dev.flush.cache.vulnerability."
resolvers = [ "ctp-dns-blocklist-vulnerability-list" ]
cache-negative-ttl = 900
cache-size = 1000
cache-answer-shuffle = "round-robin"

[groups.ctp-dns-blocklist-vulnerability-list]
type = "blocklist-v2"
blocklist-resolver = "static-refused"
blocklist-refresh = 3600
resolvers = [ "ctp-dns-blocklist-vulnerability-regex" ]
blocklist-format = "domain"
blocklist-source = [
	{format = "domain", source = "https://gcp.pihole.ctptech.dev/txt_lists/ctp-lists/tld-blacklist.list", cache-dir = "/var/cache/ctp-dns"},
	{format = "domain", source = "https://gcp.pihole.ctptech.dev/txt_lists/ctp-lists/vulnerability-blacklist.list", cache-dir = "/var/cache/ctp-dns" },
]

[groups.ctp-dns-blocklist-vulnerability-regex]
type = "blocklist-v2"
blocklist-resolver = "static-refused"
blocklist-refresh = 3600
resolvers = [ "ctp-dns-cached-front" ]
blocklist-format = "regexp"
blocklist-source = [
	{format = "regexp", source = "https://gcp.pihole.ctptech.dev/txt_lists/ctp-lists/vulnerability-blacklist.regex", cache-dir = "/var/cache/ctp-dns" },
]

