[groups.ctp-dns-blocklist]
type = "blocklist-v2"
blocklist-resolver = "static-servfail"
blocklist-refresh = 86400
resolvers = [ "ctp-dns-failover" ]
#   {format = "regexp", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/blocklistproject/routedns.blocklist.domain.list"},
blocklist-source = [
#       {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/blocklistproject/routedns.blocklist.domain.list", cache-dir = "/var/cache/ctp-dns"},
        {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/deugniets/routedns.blocklist.domain.list", cache-dir = "/var/tmp/ctp-dns"},
        {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/easylist/routedns.blocklist.domain.list", cache-dir = "/var/cache/ctp-dns"},
        {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/cloak/routedns.blocklist.domain.list", cache-dir = "/var/cache/ctp-dns"},
#       {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/malicious-dom/routedns.blocklist.domain.list", cache-dir = "/var/cache/ctp-dns"},
        {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/malicious-dom/routedns.blocklist.gafam.domain.list", cache-dir = "/var/cache/ctp-dns"},
        {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/cloak/routedns.blocklist.optimized.domain.list", cache-dir = "/var/cache/ctp-dns"},
        {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/cloak/routedns.blocklist.gafam.domain.list", cache-dir = "/var/cache/ctp-dns"},
        {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/cloak/routedns.blocklist.top-n.domain.list", cache-dir = "/var/cache/ctp-dns"},
        {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/covid/routedns.blocklist.domain.list", cache-dir = "/var/cache/ctp-dns"},
        {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/maltrail/routedns.blocklist.domain.list", cache-dir = "/var/cache/ctp-dns"},
        {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/nextdns-recommended/routedns.blocklist.domain.list", cache-dir = "/var/cache/ctp-dns"},
        {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/nextdns/routedns.blocklist.domain.list", cache-dir = "/var/cache/ctp-dns"},
        {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/typosquat/routedns.blocklist.domain.list", cache-dir = "/var/cache/ctp-dns"},
        {format = "domain", source = "/var/tmp/ctp-dns/lists/black/domains.txt", cache-dir = "/var/cache/ctp-dns"},

#       {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/oisd/routedns.blocklist.domain.list", cache-dir = "/var/cache/ctp-dns"},
#       {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/nrd/routedns.blocklist.domain.list", cache-dir = "/var/cache/ctp-dns"},
#       {format = "domain", source = "", cache-dir = "/var/cache/ctp-dns"},
]
allowlist-refresh = 900
#allowlist-resolver = "ctp-dns-group" 
allowlist-source = [
    {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/deugniets/routedns.allowlist.domain.list", cache-dir = "/var/cache/ctp-dns"},
    {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/whitelist/routedns.allowlist.domain.list", cache-dir = "/var/cache/ctp-dns"},
    {format = "domain", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/whitelist/routedns.allowlist.domain.list", cache-dir = "/var/cache/ctp-dns"},
    {format = "domain", source = "/var/tmp/ctp-dns/lists/white/domains.txt", cache-dir = "/var/cache/ctp-dns"}, 
#    {format = "regexp", source = "https://raw.githubusercontent.com/cbuijs/accomplist/master/deugniets/routedns.allowlist.regexp.list", cache-dir = "/var/cache/ctp-dns"},
]

