

# 300000 / 60 = 5000 RPS (Request Per Seconds)
# 150000 / 60 = 2500 RPS (Request Per Seconds)
# 90000 / 60 = 1500 RPS (Request Per Seconds)
# 60000 / 60 = 1000 RPS (Request Per Seconds)
# 30000 / 60 = 500 RPS (Request Per Seconds)

[groups.client-listener-rrl-standard]
type = "rate-limiter"
#resolvers = [ "root-router" ]
resolvers = [ "ctp-dns-blocklist-vulnerability" ]
limit-resolver = "drop-all"
requests = 2000
window = 15
prefix4 = 32
prefix6 = 64

[groups.drop-all]
type = "drop"
