# RAW
[resolvers.google-dns-ip-1-tcp]
address = "8.8.8.8:53"
protocol = "tcp"
[resolvers.google-dns-ip-1-udp]
address = "8.8.8.8:53"
protocol = "udp"

[resolvers.google-dns-ip-2-tcp]
address = "8.8.4.4:53"
protocol = "tcp"
[resolvers.google-dns-ip-2-udp]
address = "8.8.4.4:53"
protocol = "udp"


[resolvers.cloudflare-ip-1-tcp]
address = "1.1.1.1:53"
protocol = "tcp"
[resolvers.cloudflare-ip-1-udp]
address = "1.1.1.1:53"
protocol = "udp"

[resolvers.cloudflare-ip-2-tcp]
address = "1.0.0.1:53"
protocol = "tcp"
[resolvers.cloudflare-ip-2-udp]
address = "1.0.0.1:53"
protocol = "udp"

# OpenDNS plain DNS (resolver1.opendns.com)
[resolvers.opendns-udp-1]
address = "208.67.222.222:53"
protocol = "udp"

# OpenDNS plain DNS (resolver2.opendns.com)
[resolvers.opendns-udp-2]
address = "208.67.222.220:53"
protocol = "udp"


# Other 
[resolvers.google-dns-gcloud-private-ip-tcp]
address = "169.254.169.254:53"
protocol = "tcp"
[resolvers.google-dns-gcloud-private-ip-udp]
address = "169.254.169.254:53"
protocol = "udp"

[resolvers.unbound-failover-tcp]
address = "127.0.0.1:5053"
protocol = "tcp"
[resolvers.unbound-failover-udp]
address = "127.0.0.1:5053"
protocol = "udp"



# Encrypted
# DoQ
[resolvers.cloudflare-doh-quic]
address = "https://cloudflare-dns.com/dns-query"
protocol = "doh"
transport = "quic"

# Adguard DNS-over-QUIC
[resolvers.adguard-doq]
address = "dns-unfiltered.adguard.com:8853"
protocol = "doq"


# DoT
[resolvers.cloudflare-dot-1]
address = "1.1.1.2:853"
protocol = "dot"

[resolvers.cloudflare-dot-2]
address = "1.0.0.2:853"
protocol = "dot"

[resolvers.google-dot-1]
address = "8.8.8.8:853"
protocol = "dot"

[resolvers.google-dot-2]
address = "8.8.4.4:853"
protocol = "dot"

[resolvers.adguard-dot-1]
address = "94.140.14.14:853"
protocol = "dot"

[resolvers.adguard-dot-2]
address = "94.140.15.15:853"
protocol = "dot"

# Quad9 DNS-over-TLS
[resolvers.quad9-dot]
address = "9.9.9.9:853"
protocol = "dot"

# CleanBrowsing DoT resolver
[resolvers.cleanbrowsing-dot]
address = "family-filter-dns.cleanbrowsing.org:853"
protocol = "dot"

# DTLS
[resolvers.cloudflare-dtls-1]
address = "1.1.1.2:853"
protocol = "dtls"

[resolvers.cloudflare-dtls-2]
address = "1.0.0.2:853"
protocol = "dtls"

[resolvers.google-dtls-1]
address = "8.8.8.8:853"
protocol = "dtls"

[resolvers.google-dtls-2]
address = "8.8.4.4:853"
protocol = "dtls"

[resolvers.adguard-dtls-1]
address = "94.140.14.14:853"
protocol = "dtls"

[resolvers.adguard-dtls-2]
address = "94.140.15.15:853"
protocol = "dtls"


# DoH
# Quad9 DNS-over-HTTP using the POST method
[resolvers.quad9-doh-post]
address = "https://9.9.9.9/dns-query{?dns}"
protocol = "doh"
# Google DNS-over-HTTP using the POST method
[resolvers.google-doh-post]
address = "https://dns.google/dns-query"
protocol = "doh"

# Google DNS-over-HTTP using the GET method
[resolvers.google-doh-get]
address = "https://dns.google/dns-query{?dns}"
protocol = "doh"
doh = { method = "GET" }

# Google DNS-over-HTTP with bootstrapping to avoid initial lookup
[resolvers.google-doh-post-bootstrap]
address = "https://dns.google/dns-query"
protocol = "doh"
bootstrap-address = "8.8.8.8"


# dnscrypt.ca server-1, DoH-GET
[resolvers.dnscrypt-1-doh-get]
address = "https://dns1.dnscrypt.ca:453/dns-query{?dns}"
protocol = "doh"
doh = { method = "GET" }

# dnscrypt.ca server-2, DoH-GET
[resolvers.dnscrypt-2-doh-get]
address = "https://dns2.dnscrypt.ca:453/dns-query{?dns}"
protocol = "doh"
doh = { method = "GET" }

# dnscrypt.ca server-1, DoH-POST
[resolvers.dnscrypt-1-doh-post]
address = "https://dns1.dnscrypt.ca:453/dns-query"
protocol = "doh"

# dnscrypt.ca server-2, DoH-POST
[resolvers.dnscrypt-2-doh-post]
address = "https://dns2.dnscrypt.ca:453/dns-query"
protocol = "doh"

# Cloudflare DNS-over-HTTPS using the POST method
[resolvers.cloudflare-doh-1-1-1-1-post]
address = "https://cloudflare-dns.com/dns-query"
protocol = "doh"
bootstrap-address = "1.1.1.1"

[resolvers.cloudflare-doh-1-0-0-1-post]
address = "https://cloudflare-dns.com/dns-query"
protocol = "doh"
bootstrap-address = "1.0.0.1"

# Cloudflare DNS-over-HTTPS using the GET method
[resolvers.cloudflare-doh-1-1-1-1-get]
address = "https://cloudflare-dns.com/dns-query{?dns}"
protocol = "doh"
doh = { method = "GET" }
bootstrap-address = "1.1.1.1"

[resolvers.cloudflare-doh-1-0-0-1-get]
address = "https://cloudflare-dns.com/dns-query{?dns}"
protocol = "doh"
doh = { method = "GET" }
bootstrap-address = "1.0.0.1"
