resolvers = [ "ctp-dns-local-master-tcp", "ctp-dns-local-master-udp", " ]

[resolvers.ctp-dns-local-master-tcp]
address = "192.168.44.250:53"
protocol = "tcp"
[resolvers.ctp-dns-local-master-udp]
address = "192.168.44.250:53"
protocol = "udp"

