
[resolvers.ctp-dns-local-master-tcp]
address = "192.168.44.250:53"
protocol = "tcp"
[resolvers.ctp-dns-local-master-udp]
address = "192.168.44.250:53"
protocol = "udp"


[groups.ctp-dns-group]
resolvers = [
	"ctp-dns-local-master-tcp",
	"ctp-dns-local-master-udp",
	"ctp-dns_gcp-dot-ip-1",
	"ctp-dns_gcp-dot-ip-2",
	"ctp-dns_gcp-dtls-ip-1",
	"ctp-dns_gcp-dtls-ip-2",
	"ctp-dns_gcp-doh-post-ip-1",
	"ctp-dns_gcp-doh-post-ip-2",
	"ctp-dns_gcp-doh-get-ip-1",
	"ctp-dns_gcp-doh-get-ip-2",
	"ctp-dns_gcp-doh-quic-post-ip-1",
	"ctp-dns_gcp-doh-quic-post-ip-2",
	"ctp-dns_gcp-doh-quic-get-ip-1",
	"ctp-dns_gcp-doh-quic-get-ip-2",
	"ctp-dns_gcp-quic-ip-1",
	"ctp-dns_gcp-quic-ip-2"
]
type = "fastest"

[groups.ctp-dns-group-local]
resolvers = [
	"ctp-dns-local-master-tcp",
	"ctp-dns-local-master-udp",
]
type = "fastest"


[groups.ctp-dns-group]
resolvers = [
	"ctp-dns-local-master-tcp",
	"ctp-dns-local-master-udp",
	"ctp-dns_gcp-dot-ip-1",
	"ctp-dns_gcp-dot-ip-2",
	"ctp-dns_gcp-dtls-ip-1",
	"ctp-dns_gcp-dtls-ip-2",
	"ctp-dns_gcp-doh-post-ip-1",
	"ctp-dns_gcp-doh-post-ip-2",
	"ctp-dns_gcp-doh-get-ip-1",
	"ctp-dns_gcp-doh-get-ip-2",
	"ctp-dns_gcp-doh-quic-post-ip-1",
	"ctp-dns_gcp-doh-quic-post-ip-2",
	"ctp-dns_gcp-doh-quic-get-ip-1",
	"ctp-dns_gcp-doh-quic-get-ip-2",
	"ctp-dns_gcp-quic-ip-1",
	"ctp-dns_gcp-quic-ip-2"
]
type = "fastest"

[groups.ctp-dns-group-local]
resolvers = [
	"ctp-dns-local-master-tcp",
	"ctp-dns-local-master-udp",
]
type = "fastest"

