# GOOGLE
[resolvers.google-dot-ipv6-ip-1]
address = "dns.google:853"
bootstrap-address = "2001:4860:4860:0:0:0:0:8888"
protocol = "dot"

[resolvers.google-dtls-ipv6-ip-1]
address = "dns.google:853"
bootstrap-address = "2001:4860:4860:0:0:0:0:8888"
protocol = "dtls"

[resolvers.google-dot-ipv6-ip-2]
address = "dns.google:853"
bootstrap-address = "2001:4860:4860:0:0:0:0:8844"
protocol = "dot"

[resolvers.google-dtls-ipv6-ip-2]
address = "dns.google:853"
bootstrap-address = "2001:4860:4860:0:0:0:0:8844"
protocol = "dtls"

# Cloudflare
[resolvers.cloudflare-dot-ipv6-ip-1]
address = "one.one.one.one:853"
bootstrap-address = "2606:4700:4700::1111"
protocol = "dot"

[resolvers.cloudflare-dtls-ipv6-ip-1]
address = "one.one.one.one:853"
bootstrap-address = "2606:4700:4700::1111"
protocol = "dtls"

[resolvers.cloudflare-dot-ipv6-ip-2]
address = "one.one.one.one:853"
bootstrap-address = "2606:4700:4700::1001"
protocol = "dot"

[resolvers.cloudflare-dtls-ipv6-ip-2]
address = "one.one.one.one:853"
bootstrap-address = "2606:4700:4700::1001"
protocol = "dtls"



# Cloudlfare anit malware

[resolvers.cloudflare-malware-dot-ipv6-ip-1]
address = "one.one.one.one:853"
bootstrap-address = "2606:4700:4700::1112"
protocol = "dot"

[resolvers.cloudflare-malware-dtls-ipv6-ip-1]
address = "one.one.one.one:853"
bootstrap-address = "2606:4700:4700::1112"
protocol = "dtls"

[resolvers.cloudflare-maleware-dot-ipv6-ip-2]
address = "one.one.one.one:853"
bootstrap-address = "2606:4700:4700::1002"
protocol = "dot"

[resolvers.cloudflare-malware-dtls-ipv6-ip-2]
address = "one.one.one.one:853"
bootstrap-address = "2606:4700:4700::1002"
protocol = "dtls"

