#!/bin/bash
source $PROG/all-scripts-exports.sh
what_system

OUT_FILE=/etc/modprobe.d/ctp-dns-blacklist-unneeded.conf
MODULES_LIST=$(find /lib/modules/$(uname -r) -type f -name '*.ko' | rev | awk -F/ '{print $1}' | rev | cut -d. -f 1)
MODULES_VIDEO_LIST=$(find /lib/modules/$(uname -r) -type f -name '*.ko' | grep -i video | rev | awk -F/ '{print $1}' | rev | cut -d. -f 1)
MODULES_INPUT_LIST=$(find /lib/modules/$(uname -r) -type f -name '*.ko' | grep -i input | rev | awk -F/ '{print $1}' | rev | cut -d. -f 1)
MODULES_SOUND_LIST=$(find /lib/modules/$(uname -r) -type f -name '*.ko' | grep -i sound | rev | awk -F/ '{print $1}' | rev | cut -d. -f 1)
if [[ $IS_VM == false ]]; then
	MODULES_VIRTO_LIST=$(find /lib/modules/$(uname -r) -type f -name '*.ko' | grep -i virtio | rev | awk -F/ '{print $1}' | rev | cut -d. -f 1)
fi

echo """# Generated by: $scriptName
# Generated at: `date`

""" | sudo tee $OUT_FILE
declare -a modprobes
modprobes=(
	 $(printf '%s\n' "$MODULES_LIST" | grep -i firewire)
	 $(printf '%s\n' "$MODULES_LIST" | grep -i 1394)
	 $(printf '%s\n' "$MODULES_LIST" | grep -iE 'fb((_base)?)$')
	 $(printf '%s\n' "$MODULES_LIST" | grep -i hid)
	 $(printf '%s\n' "$MODULES_LIST" | grep -i hid)
	 $(printf '%s\n' "$MODULES_LIST" | grep -i megaraid)
	 $(printf '%s\n' "$MODULES_LIST" | grep -iE '^ml')
	 $(printf '%s\n' "$MODULES_LIST" | grep -i matroxfb)
	 $(printf '%s\n' "$MODULES_LIST" | grep -iE ^dm)
	 $(printf '%s\n' "$MODULES_LIST" | grep -i target)
	 $(printf '%s\n' "$MODULES_LIST" | grep -i 9pnet)
	 $(printf '%s\n' "$MODULES_LIST" | grep -i midi)
	 $(printf '%s\n' "$MODULES_LIST" | grep -i snd)
	 $(printf '%s\n' "$MODULES_LIST" | grep -i kvm)
	 $(printf '%s\n' "$MODULES_VIDEO_LIST")
	 $(printf '%s\n' "$MODULES_INPUT_LIST")
	 $(printf '%s\n' "$MODULES_SOUND_LIST")
	 $(printf '%s\n' "$MODULES_VIRTO_LIST")
)

for module in ${modprobes[@]}
do
echo "On Module $module blacklisting and prevetting autoload"

echo """
# BLACKLISTING AND PROVETING AUTO INSTALL $module
blacklist $module
install $module /bin/false
""" | sudo tee -a $OUT_FILE
echo "done with $module"

done
