[groups.ctp-dns-blocklist-local]
type = "blocklist-v2"
blocklist-resolver = "static-servfail"
blocklist-refresh = 86400
blocklist-format = "domain"
resolvers = [ "ctp-dns-fail-back" ]
blocklist-source = [
        {format = "domain", source = "/var/tmp/ctp-dns/lists/black/ads.txt"},
        {format = "domain", source = "/var/tmp/ctp-dns/lists/black/malware-typo.txt"},
        {format = "domain", source = "/var/tmp/ctp-dns/lists/black/malware.txt"},
        {format = "domain", source = "/var/tmp/ctp-dns/lists/black/tracking.txt"},
        {format = "domain", source = "/var/tmp/ctp-dns/lists/black/scam.txt"},
]
