

[resolvers.ctp-dns-local-master-tcp]
address = "192.168.44.250:53"
protocol = "tcp"
[resolvers.ctp-dns-local-master-udp]
address = "192.168.44.250:53"
protocol = "udp"
edns0-udp-size = 1460

[groups.ctp-dns-local-master-truncate-retry]
type = "truncate-retry"
resolvers = [ "ctp-dns-local-master-udp" ]
retry-resolver = "ctp-dns-local-master-tcp"



# DNS
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-tcp]
address = "192.168.99.9:53"
protocol = "tcp"
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-udp]
address = "192.168.99.9:53"
protocol = "udp"
edns0-udp-size = 1460

# DoT
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-dot]
address = "gcp.ctptech.dev:853"
protocol = "dot"
bootstrap-address = "192.168.99.9"
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-dot-nginx]
address = "gcp.ctptech.dev:11853"
protocol = "dot"
bootstrap-address = "192.168.99.9"

# DTLS
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-dtls]
address = "gcp.ctptech.dev:853"
protocol = "dtls"
bootstrap-address = "192.168.99.9"
edns0-udp-size = 1460

# QUIC
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-doq]
address = "gcp.ctptech.dev:784"
protocol = "doq"
bootstrap-address = "192.168.99.9"
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-doh-doq]
address = "gcp.ctptech.dev:1443"
protocol = "doh"
transport = "quic"
bootstrap-address = "192.168.99.9"

# DoH
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-doh-get]
address = "gcp.ctptech.dev:4443"
protocol = "doh"
doh = { method = "GET" }
bootstrap-address = "192.168.99.9"
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-doh-post]
address = "gcp.ctptech.dev:4443"
protocol = "doh"
bootstrap-address = "192.168.99.9"

# GROUPS
[groups.ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-truncate-retry-raw]
type = "truncate-retry"
resolvers = [ "ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-udp" ]
retry-resolver = "ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-tcp"

[groups.ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-truncate-retry-encrypted]
type = "truncate-retry"
resolvers = [ "ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-dtls" ]
retry-resolver = "ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-dot"




# DNS
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-tcp]
address = "100.86.69.129:53"
protocol = "tcp"
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-udp]
address = "100.86.69.129:53"
protocol = "udp"
edns0-udp-size = 1460

# DoT
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-dot]
address = "gcp.ctptech.dev:853"
protocol = "dot"
bootstrap-address = "100.86.69.129"
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-dot-nginx]
address = "gcp.ctptech.dev:11853"
protocol = "dot"
bootstrap-address = "100.86.69.129"

# DTLS
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-dtls]
address = "gcp.ctptech.dev:853"
protocol = "dtls"
bootstrap-address = "100.86.69.129"
edns0-udp-size = 1460

# QUIC
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-doq]
address = "gcp.ctptech.dev:784"
protocol = "doq"
bootstrap-address = "100.86.69.129"
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-doh-doq]
address = "gcp.ctptech.dev:1443"
protocol = "doh"
transport = "quic"
bootstrap-address = "100.86.69.129"

# DoH
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-doh-get]
address = "gcp.ctptech.dev:4443"
protocol = "doh"
doh = { method = "GET" }
bootstrap-address = "100.86.69.129"
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-doh-post]
address = "gcp.ctptech.dev:4443"
protocol = "doh"
bootstrap-address = "100.86.69.129"

# GROUPS
[groups.ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-truncate-retry-raw]
type = "truncate-retry"
resolvers = [ "ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-udp" ]
retry-resolver = "ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-tcp"

[groups.ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-truncate-retry-encrypted]
type = "truncate-retry"
resolvers = [ "ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-dtls" ]
retry-resolver = "ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-dot"




# DNS
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-tcp]
address = "100.71.239.28:53"
protocol = "tcp"
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-udp]
address = "100.71.239.28:53"
protocol = "udp"
edns0-udp-size = 1460

# DoT
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-dot]
address = "gcp.ctptech.dev:853"
protocol = "dot"
bootstrap-address = "100.71.239.28"
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-dot-nginx]
address = "gcp.ctptech.dev:11853"
protocol = "dot"
bootstrap-address = "100.71.239.28"

# DTLS
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-dtls]
address = "gcp.ctptech.dev:853"
protocol = "dtls"
bootstrap-address = "100.71.239.28"
edns0-udp-size = 1460

# QUIC
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-doq]
address = "gcp.ctptech.dev:784"
protocol = "doq"
bootstrap-address = "100.71.239.28"
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-doh-doq]
address = "gcp.ctptech.dev:1443"
protocol = "doh"
transport = "quic"
bootstrap-address = "100.71.239.28"

# DoH
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-doh-get]
address = "gcp.ctptech.dev:4443"
protocol = "doh"
doh = { method = "GET" }
bootstrap-address = "100.71.239.28"
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-doh-post]
address = "gcp.ctptech.dev:4443"
protocol = "doh"
bootstrap-address = "100.71.239.28"

# GROUPS
[groups.ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-truncate-retry-raw]
type = "truncate-retry"
resolvers = [ "ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-udp" ]
retry-resolver = "ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-tcp"

[groups.ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-truncate-retry-encrypted]
type = "truncate-retry"
resolvers = [ "ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-dtls" ]
retry-resolver = "ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-dot"




# DNS
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-tcp]
address = "10.128.0.9:53"
protocol = "tcp"
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-udp]
address = "10.128.0.9:53"
protocol = "udp"
edns0-udp-size = 1460

# DoT
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-dot]
address = "gcp.ctptech.dev:853"
protocol = "dot"
bootstrap-address = "10.128.0.9"
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-dot-nginx]
address = "gcp.ctptech.dev:11853"
protocol = "dot"
bootstrap-address = "10.128.0.9"

# DTLS
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-dtls]
address = "gcp.ctptech.dev:853"
protocol = "dtls"
bootstrap-address = "10.128.0.9"
edns0-udp-size = 1460

# QUIC
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-doq]
address = "gcp.ctptech.dev:784"
protocol = "doq"
bootstrap-address = "10.128.0.9"
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-doh-doq]
address = "gcp.ctptech.dev:1443"
protocol = "doh"
transport = "quic"
bootstrap-address = "10.128.0.9"

# DoH
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-doh-get]
address = "gcp.ctptech.dev:4443"
protocol = "doh"
doh = { method = "GET" }
bootstrap-address = "10.128.0.9"
[resolvers.ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-doh-post]
address = "gcp.ctptech.dev:4443"
protocol = "doh"
bootstrap-address = "10.128.0.9"

# GROUPS
[groups.ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-truncate-retry-raw]
type = "truncate-retry"
resolvers = [ "ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-udp" ]
retry-resolver = "ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-tcp"

[groups.ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-truncate-retry-encrypted]
type = "truncate-retry"
resolvers = [ "ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-dtls" ]
retry-resolver = "ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-dot"




[groups.ctp-dns-group]
resolvers = [
	"ctp-dns-local-master-tcp",
	"ctp-dns-local-master-udp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-tcp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-udp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-dot",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-dot-nginx",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-dtls",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-doq",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-doh-doq",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-doh-get",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-doh-post",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-tcp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-udp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-dot",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-dot-nginx",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-dtls",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-doq",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-doh-doq",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-doh-get",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-doh-post",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-tcp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-udp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-dot",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-dot-nginx",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-dtls",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-doq",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-doh-doq",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-doh-get",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-doh-post",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-tcp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-udp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-dot",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-dot-nginx",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-dtls",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-doq",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-doh-doq",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-doh-get",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-doh-post",
	"ctp-dns_gcp-dot-ip-1",
	"ctp-dns_gcp-dot-ip-2",
	"ctp-dns_gcp-dtls-ip-1",
	"ctp-dns_gcp-dtls-ip-2",
	"ctp-dns_gcp-doh-post-ip-1",
	"ctp-dns_gcp-doh-post-ip-2",
	"ctp-dns_gcp-doh-get-ip-1",
	"ctp-dns_gcp-doh-get-ip-2",
	"ctp-dns_gcp-doh-quic-post-ip-1",
	"ctp-dns_gcp-doh-quic-post-ip-2",
	"ctp-dns_gcp-doh-quic-get-ip-1",
	"ctp-dns_gcp-doh-quic-get-ip-2",
	"ctp-dns_gcp-quic-ip-1",
	"ctp-dns_gcp-quic-ip-2",
]
type = "fastest"

[groups.ctp-dns-group-local]
resolvers = [
	"ctp-dns-local-master-tcp",
	"ctp-dns-local-master-udp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-tcp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-udp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-dot",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-dot-nginx",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-dtls",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-doq",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-doh-doq",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-doh-get",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-192-168-99-9-doh-post",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-tcp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-udp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-dot",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-dot-nginx",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-dtls",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-doq",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-doh-doq",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-doh-get",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-86-69-129-doh-post",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-tcp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-udp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-dot",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-dot-nginx",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-dtls",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-doq",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-doh-doq",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-doh-get",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-100-71-239-28-doh-post",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-tcp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-udp",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-dot",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-dot-nginx",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-dtls",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-doq",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-doh-doq",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-doh-get",
	"ctp-dns-local-master-gcp-or-vpn-tunnel-10-128-0-9-doh-post",
]
type = "fastest"

# CTP INSTALL -- DO NOT REMOVE THIS UNLESS YOU PLAN ON REMOVING INSTALL AND REINSTALLING
# NO CHANGES
